[DEVOPS-479]  Temporarily disable 'report-server' evaluation, due to:
BotoServerError: 409 Conflict
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>EntityAlreadyExists</Code>
    <Message>Role with name charon-456a3159-9b9f-11e7-bc0c-06258a1e40fd-report-role already exists.</Message>
  </Error>
  <RequestId>5df41864-bedc-11e7-b018-3f051611aede</RequestId>
</ErrorResponse>